import { BaseTool, ToolSchema } from "./types";

export class TelegramAlertTool extends BaseTool {
  readonly name = "telegram_alert";
  readonly description = "Send a professional trading alert to the user's Telegram channel with full SMC setup details.";

  readonly schema: ToolSchema = {
    name: "telegram_alert",
    description: "Send a professional trading alert to Telegram.",
    args: {
      symbol: { type: "string", description: "The ticker symbol (e.g., B-ETH_USDT)", required: true },
      direction: { type: "string", description: "Long or Short", required: true },
      setupName: { type: "string", description: "e.g., 15m Buyside Sweep + ChoCh", required: true },
      entryRange: { type: "string", description: "Target entry price range", required: true },
      stopLoss: { type: "string", description: "Stop loss price", required: true },
      takeProfit: { type: "string", description: "Take profit price(s)", required: true },
      analysisSummary: { type: "string", description: "Brief SMC logic for the trade", required: true }
    }
  };

  async execute(args: Record<string, unknown>): Promise<string> {
    const { symbol, direction, setupName, entryRange, stopLoss, takeProfit, analysisSummary } = args;
    
    const botToken = process.env.TELEGRAM_BOT_TOKEN;
    const chatId = process.env.TELEGRAM_CHAT_ID;

    if (!botToken || !chatId) {
      return "Error: TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not configured in .env";
    }

    const message = `
🚀 *NEW FUTURES SETUP ALERT* 🚀

*Strategy:* ${setupName}
*Symbol:* \`${symbol}\`
*Direction:* ${direction === 'Long' ? '🟢 LONG' : '🔴 SHORT'}

🎯 *Entry:* ${entryRange}
🛑 *Stop Loss:* ${stopLoss}
💰 *Take Profit:* ${takeProfit}

📝 *Analysis:*
${analysisSummary}

_Generated by AI Workspace SMC Engine_
    `.trim();

    try {
      const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
      const response = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chat_id: chatId,
          text: message,
          parse_mode: "Markdown"
        })
      });

      if (!response.ok) {
        const error = await response.text();
        return `Failed to send Telegram alert: ${error}`;
      }

      return `Successfully sent Telegram alert for ${symbol} (${direction})`;
    } catch (error: any) {
      return `Error sending Telegram alert: ${error.message}`;
    }
  }
}
