export type TelegramTradeAlertArgs = {
  symbol: string;
  direction: 'Long' | 'Short';
  setupName: string;
  entryRange: string;
  stopLoss: string;
  takeProfit: string;
  analysisSummary: string;
  riskReward?: string;
};

function buildTelegramMarkdown(args: TelegramTradeAlertArgs): string {
  const rr = args.riskReward ? `\n📐 *R:R:* ${args.riskReward}` : '';
  return `
🚀 *NEW FUTURES SETUP ALERT* 🚀

*Strategy:* ${args.setupName}
*Symbol:* \`${args.symbol}\`
*Direction:* ${args.direction === 'Long' ? '🟢 LONG' : '🔴 SHORT'}

🎯 *Entry:* ${args.entryRange}
🛑 *Stop Loss:* ${args.stopLoss}
💰 *Take Profit:* ${args.takeProfit}${rr}

📝 *Analysis:*
${args.analysisSummary}

_Generated by AI Workspace SMC Engine_
  `.trim();
}

export async function sendTelegramTradeAlert(
  args: TelegramTradeAlertArgs,
  env: NodeJS.ProcessEnv = process.env
): Promise<{ ok: true } | { ok: false; error: string }> {
  const botToken = env.TELEGRAM_BOT_TOKEN;
  const chatId = env.TELEGRAM_CHAT_ID;
  if (!botToken || !chatId) {
    return { ok: false, error: 'TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set' };
  }
  const text = buildTelegramMarkdown(args);
  try {
    const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text,
        parse_mode: 'Markdown',
      }),
    });
    if (!response.ok) {
      return { ok: false, error: await response.text() };
    }
    return { ok: true };
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }
}
